### ISSUE TITLE
gpu error when train word2vec

### ISSUE THREAD

**Issue by lixiangnlp** [pfnet/chainer#305] opened 2015-08-11 08:05 UTC
I ran the command " python train_word2vec.py  --gpu=0", and got the error

Traceback (most recent call last):
  File "train_word2vec.py", line 172, in <module>
    loss = train_model(dataset, position)
  File "train_word2vec.py", line 91, in skip_gram
    loss_i = loss_func(e, t)
  File "/home/lixiang/anaconda/lib/python2.7/site-packages/chainer/function.py", line 166, in __call__
    outputs = self.forward(in_data)
  File "/home/lixiang/anaconda/lib/python2.7/site-packages/chainer/function.py", line 252, in forward
    return self.forward_gpu(inputs)
  File "/home/lixiang/anaconda/lib/python2.7/site-packages/chainer/function.py", line 288, in forward_gpu
    raise NotImplementedError()
NotImplementedError
terminate called after throwing an instance of 'pycuda::error'
  what():  explicit_context_dependent failed: invalid device context - no currently active context?

**Comment by delta2323** [comment] 2015-08-11 09:16
By default, `train_word2vec.py` uses `BinaryHierachicalSoftmax` (HSM) function when calculating the training loss. In current Chainer, HSM does not support GPU mode (See PR #270 for reference). That is why this error had happened.

If it is acceptable, you can use `NegativeSampling` or the combination of `Linear` function and  `SoftmaxCrossEntropy` as a loss function instead. These modules support GPU mode.
The loss function is specified by `out-type` option.

**Comment by unnonouno** [comment] 2015-08-18 05:43
We fixed GPU mode of HSM in #264. You can use word2vec example with the current master branch. Please try it!

**Comment by delta2323** [comment] 2015-08-25 07:11
@lixiangnlp How is this problem going? I would like you to close this issue if the problem is solved.

**Closed** 2015-08-26 01:14 UTC
