### ISSUE TITLE
Adam: Numerical result out of range

### ISSUE THREAD

**Issue by sergsb** [pfnet/chainer#2388] opened 2017-03-09 13:58 UTC
Hi,
I use chainer v. 1.21.1 I faced a strange error in Adam optimizer. The optimizer fails during training with this exception.
```
  File "train.py", line 96, in <module>
    trainer.run()
  File "~/.local/lib/python2.7/site-packages/chainer/training/trainer.py", line 295, in run
    update()
  File "~/.local/lib/python2.7/site-packages/chainer/training/updater.py", line 174, in update
    self.update_core()
  File "~/.local/lib/python2.7/site-packages/chainer/training/updater.py", line 186, in update_core
    optimizer.update(loss_func, *in_vars)
  File "~/.local/lib/python2.7/site-packages/chainer/optimizer.py", line 413, in update
    self.update_one(param, states[name])
  File "~/.local/lib/python2.7/site-packages/chainer/optimizer.py", line 429, in update_one
    self.update_one_gpu(param, state)
  File "~/.local/lib/python2.7/site-packages/chainer/optimizers/adam.py", line 44, in update_one_gpu
    'adam')(param.grad, self.lr, 1 - self.beta1, 1 - self.beta2,
  File "~/.local/lib/python2.7/site-packages/chainer/optimizers/adam.py", line 49, in lr
    fix1 = 1. - self.beta1 ** self.t
OverflowError: (34, ‘Numerical result out of range')

```
It happens in only one machine (Python 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC] on linux2) on cluster, others run normally.

**Comment by delta2323** [comment] 2017-03-13 15:36
Thank you for reporting the problem. Could you try the following calculations and share the results?

* `sys.float_info.min`
* `10.0 ** 300`, `10.0 ** 310`
* `10.0 ** -300`, `10.0 ** -310`

**Comment by sergsb** [comment] 2017-03-16 10:12
Hi,

```
Python 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.

import sys
sys.float_info.max
1.7976931348623157e+308

sys.float_info.min
2.2250738585072014e-308

10.**300
1e+300

10.**-300
1e-300

10.**-310
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: (34, 'Numerical result out of range')

10.**310
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: (34, 'Numerical result out of range')
```

**Comment by delta2323** [comment] 2017-03-22 09:12
Thank you for sharing the result. It seems the error is caused by `self.beta1 ** self.t` being exceeded the value of `sys.float_info.min` or `max`. I believe at least the underflow problem will be solved if we replace `self.beta1 ** self.t` with `math.pow(self.beta1, self.t)`.

**Comment by monotaro3** [comment] 2017-04-26 09:01
I faced the same error and your solution works well now. Thanks. It's interesting that 10.**-310 returns an error in one environment and doesn't in other environments. I believe it will be fixed in the near future.

**Comment by unnonouno** [comment] 2017-04-26 09:53
Behavior for underflow depends on python implementation. In cPython, `pow` is called here.
https://github.com/python/cpython/blob/2.7/Objects/floatobject.c#L922
And its error is checked at line 928: https://github.com/python/cpython/blob/2.7/Objects/floatobject.c#L928
`pow` API set `errno = ERANGE` when overflow or underflow occur: https://linux.die.net/man/3/pow
So, it can raise an OverflowError.

At line 924 it calls `PyADJUST_ERANGE1` macro: https://github.com/python/cpython/blob/2.7/Objects/floatobject.c#L924
and this macro set `errno = 0` when a returned value is `0`: https://github.com/python/cpython/blob/master/Include/pyport.h#L346
`pow` API returns `0.0` when underflow occurs. So, its error is ignored and OverflowError is not raised. But I don't know why OverflowError is not happen in @sergsb 's environment...

**Comment by monotaro3** [comment] 2017-04-26 11:59
As I ran 10.**-310 and 10.**310 in two different environments, while only 10.**310 raised OverflowError in one environment, both raised that error in the other, where chainer also raised that error. So I guess that the error I got was actually underflow error(not confirmed, but I can infer). Might it be caused by different behavior of pow()? I don't know.
Anyway, thanks for your answer :-)

**Closed** 2017-05-11 14:38 UTC
