### ISSUE TITLE
Unpooling2D function?

### ISSUE THREAD

**Issue by wkentaro** [pfnet/chainer#597] opened 2015-11-04 11:21 UTC
Do you have plan to implement unpooling2d function?

**Comment by wkentaro** [comment] 2015-11-04 11:22
I'd like to use it to construct convolutional autoencoder like [here](https://github.com/mikesj-public/convolutional_autoencoder).

**Comment by wkentaro** [comment] 2015-11-04 14:16
simple demo: https://gist.github.com/wkentaro/bb8300867a5ed6d53200

**Comment by mitmul** [comment] 2015-11-04 14:53
Duplicate of https://github.com/pfnet/chainer/pull/301

**Comment by wkentaro** [comment] 2015-11-04 15:15
I didn't notice that, but that is PR and not issue. So maybe we can keep this issue open.

**Closed** 2016-02-23 06:38 UTC
Labels: feature
